PREFIX ns0: <https://slovník.gov.cz/legislativní/sbírka/111/2009/pojem/>
CONSTRUCT {
  ?v0 a ns0:adresní-místo .
  ?v0 ns0:má-kód-adresního-místa ?v1 .
}
WHERE {
  ?v0 a ns0:adresní-místo .
  ?v0 ns0:má-kód-adresního-místa ?v1 .
}
